apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  component: phpmyadmin

resources:
  - deployment.yaml
  - service.yaml