kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          # image: mysql:latest@sha256:238cf050a7270dd6940602e70f1e5a11eeaf4e02035f445b7f613ff5e0641f7d
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql
          # livenessProbe:
          #   tcpSocket:
          #     port: mysql
          readinessProbe:
            tcpSocket:
              port: mysql
# TODO: volume